/** Textes du profil (barre latérale), de la page « Mon compte » et de la carte de Mes projets. */
export const TEXTES_MON_COMPTE = {
  titre: 'Mon compte',
  chargement: 'Chargement…',
  profil: 'Profil',
  email: 'Adresse e-mail',
  nom: 'Prénom ou nom affiché',
  enregistrer: 'Enregistrer',
  nomEnregistre: "C'est enregistré.",
  connexion: 'Connexion',
  methodeEmail: 'Code par e-mail',
  deconnecter: 'Me déconnecter',
  supprimer: 'Supprimer mon compte',
  explicationSuppression:
    'Votre compte et vos sessions sont effacés. Les projets enregistrés sur cet appareil restent là.',
  confirmerSuppression: 'Oui, supprimer mon compte',
  annuler: 'Annuler',
  seReconnecter: 'Me reconnecter',
  sansCompte: 'Sans compte',
  gratuit: 'Gratuit',
  seConnecter: 'Se connecter',
  carteTitre: 'Retrouvez vos projets sur tous vos appareils',
  carteTexte: 'Un compte par e-mail, Google ou Apple, sans mot de passe. Gratuit.',
  creerCompte: 'Créer mon compte',
  carteTitreConnecte: 'Vos projets sur tous vos appareils',
  carteTexteConnecte: 'La synchronisation arrive bientôt : vos projets restent sur cet appareil.',
} as const;
